# Generated by Django 5.1.3 on 2026-10-01 11:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_keys", "0001_initial"),
        ("app_users", "0032_alter_appuser_uid"),
        ("workspaces", "0016_alter_workspacemembership_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelApiCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_id", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Reserved"),
                            (2, "Settling"),
                            (3, "Settled"),
                            (4, "Released"),
                        ],
                        default=1,
                    ),
                ),
                ("model", models.TextField(help_text="The model ID the client sent.")),
                (
                    "litellm_model",
                    models.TextField(help_text="The LiteLLM routing ID it ran as."),
                ),
                ("call_type", models.CharField(max_length=64)),
                ("reserved_credits", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=18, null=True
                    ),
                ),
                ("charged_credits", models.IntegerField(default=0)),
                ("usage", models.JSONField(blank=True, default=dict)),
                ("settled_by", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_keys.apikey",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app_users.appusertransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_users.appuser",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_api_calls",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"],
                        name="model_api_m_workspa_5a0f4f_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="model_api_m_status_96c52f_idx",
                    ),
                ],
            },
        ),
    ]
