# Generated by Django 5.1.3 on 2026-10-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0132_alter_publishedrun_workflow_alter_savedrun_workflow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrun",
            name="error_traceback",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The traceback of the exception that failed the run.",
            ),
        ),
    ]
