# Generated by Django 5.1.3 on 2026-09-30 08:54

import bots.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('photo_url', bots.custom_fields.CustomURLField(blank=True, default='', help_text="The UN's transparent inverted icon, drawn on a white tile.", max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SDG',
                'verbose_name_plural': 'SDGs',
                'ordering': ['number'],
            },
        ),
    ]
